-- MySQL Script generated by MySQL Workbench
-- Sun Feb 20 21:10:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PAPsite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PAPsite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PAPsite` DEFAULT CHARACTER SET utf8 ;
USE `PAPsite` ;

-- -----------------------------------------------------
-- Table `PAPsite`.`Statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`Statut` (
  `id_statut` INT NOT NULL AUTO_INCREMENT,
  `libelle_statut` VARCHAR(45) NOT NULL,
  `description_statut` VARCHAR(45) NULL,
  PRIMARY KEY (`id_statut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAPsite`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`Animal` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `nom_animal` VARCHAR(45) NOT NULL,
  `type_animal` ENUM("Chien", "Chat") NOT NULL,
  `puce_animal` INT NULL,
  `sexe` VARCHAR(45) NULL,
  `ami_chien` ENUM("oui", "non", "N/A") NULL,
  `ami_chat` ENUM("oui", "non", "N/A") NULL,
  `ami_enfant` ENUM("oui", "non", "N/A") NULL,
  `description_animal` LONGTEXT NULL,
  `adoption_description_animal` LONGTEXT NULL,
  `localisation_description_animal` LONGTEXT NULL,
  `engagement_description_animal` LONGTEXT NULL,
  `id_statut` INT NOT NULL,
  PRIMARY KEY (`id_animal`),
  CONSTRAINT `fk_Animal_Statut`
    FOREIGN KEY (`id_statut`)
    REFERENCES `PAPsite`.`Statut` (`id_statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAPsite`.`Caractere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`Caractere` (
  `id_caractere` INT NOT NULL AUTO_INCREMENT,
  `libelle_caractere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_caractere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAPsite`.`dispose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`dispose` (
  `id_caractere` INT NOT NULL,
  `id_animal` INT NOT NULL,
  PRIMARY KEY (`id_caractere`, `id_animal`),
  CONSTRAINT `fk_Caractere_has_Animal_Caractere1`
    FOREIGN KEY (`id_caractere`)
    REFERENCES `PAPsite`.`Caractere` (`id_caractere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caractere_has_Animal_Animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `PAPsite`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAPsite`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`Image` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `libelle_image` VARCHAR(45) NOT NULL,
  `url_image` VARCHAR(120) NOT NULL,
  `description_image` LONGTEXT NULL,
  `id_actualite` INT NOT NULL,
  PRIMARY KEY (`id_image`, `id_actualite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAPsite`.`Actualite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`Actualite` (
  `id_actualite` INT NOT NULL AUTO_INCREMENT,
  `libelle_actualite` VARCHAR(45) NULL,
  `date_publication_actualite` DATE NULL,
  `type_actualite` ENUM("News", "Action", "Event") NULL,
  `id_image` INT NOT NULL,
  `id_actualites` INT NOT NULL,
  PRIMARY KEY (`id_actualite`),
  CONSTRAINT `fk_Actualite_Image1`
    FOREIGN KEY (`id_image` , `id_actualites`)
    REFERENCES `PAPsite`.`Image` (`id_image` , `id_actualite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAPsite`.`contient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`contient` (
  `id_animal` INT NOT NULL,
  `id_image` INT NOT NULL,
  PRIMARY KEY (`id_animal`, `id_image`),
  CONSTRAINT `fk_Animal_has_Image_Animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `PAPsite`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_has_Image_Image1`
    FOREIGN KEY (`id_image`)
    REFERENCES `PAPsite`.`Image` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAPsite`.`associe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAPsite`.`associe` (
  `id_animal` INT NOT NULL,
  `id_actualite_animal` INT NOT NULL,
  PRIMARY KEY (`id_animal`, `id_actualite_animal`),
  CONSTRAINT `fk_Animal_has_Actualite_Animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `PAPsite`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_has_Actualite_Actualite1`
    FOREIGN KEY (`id_actualite_animal`)
    REFERENCES `PAPsite`.`Actualite` (`id_actualite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
